# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imageName: MSPR-EPSI-I1-TPRE716-2020-mspr-front
  tag: 'mspr-front'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
steps:
- task: Docker@2
  displayName: Build and push image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: app/Dockerfile
    containerRegistry: DockerServiceConnection
    tags: $(tag)
- task: tes

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
   npm install
   npm run coverage
   npm run build
  displayName: 'npm install, run coverage and build'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml