trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: MSPR-EPSI-I1-TPRE716-2020-mspr-front
  tag: 'mspr-front'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
steps:
- task: Docker@2
  displayName: Build and push image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: app/Dockerfile
    containerRegistry: DockerServiceConnection
    tags: $(tag)

- script: |
   npm install
   npm run coverage
   npm run build
  displayName: 'npm install, run coverage and build'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
